### ISSUE TITLE
FileInfo/Regex matching causes severe performance overhead in IDE experiences

### ISSUE THREAD

**Issue by sharwell** [modernuo/SerializationGenerator#5]
This path is showing up as very slow in performance traces. If possible, it would be beneficial to users to optimize this path and/or convert the source generator to `IIncrementalGenerator` so this path is executed less frequently in editing scenarios.

https://github.com/modernuo/SerializationGenerator/blob/98d0d9dd64a7f5c069f69de23e3201947f82d7c8/SerializationGenerator/SerializableMigration/SerializableMigrationSchema.cs#L85-L86

**Comment by kamronbatman** [comment]
@sharwell can you give me some pointers on how to speed this up with IIncrementalGenerator.
To give some more context, the source generator needs to import migration files (JSON files):
https://github.com/modernuo/ModernUO/blob/e148e1cabb9d5f798376712c3ce6a00fc4f230c4/Projects/UOContent/UOContent.csproj#L51

If you have ideas on how to go about doing the logic without regex that would be great too.

EDIT:
Since I am looking for `"classname.v#.json"`, I can probably use a ref struct tokenizer with `MemoryExtensions.IndexOf` and tokenize on `.`. I'll look into this after converting to the IIncrementalGenerator.

Thanks!

**Comment by sharwell** [comment]
@kamronbatman If you implement `IIncrementalGenerator` (Roslyn 4.0+), you can register a callback for [`AdditionalTextsProvider`](https://github.com/dotnet/roslyn/blob/62f85a44fe5b08c50132c887892ea856e337d768/src/Compilers/Core/Portable/SourceGeneration/IncrementalContexts.cs#L37) and you'll only get calls when a change occurs to one of these files (added, removed, or content changed). In other cases, the source generator output from the previous run will be reused instead of recalculated.

@chsienki do we have a general introduction page for incremental generators to point users to?

**Comment by chsienki** [comment]
Docs are here: https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md

**Comment by kamronbatman** [comment]
Thanks, I was reviewing that last night. I understand the pipeline generally speaking. My only hang up is that the generator currently enumerates all classes that _will_ be serializable so it knows how determine the proper strategy in some situations.
So I'll work on a way around that since it seems like it would not be in the spirit of the isolation used to gain performance increases with the incremental generators.
